//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the memsense_imu package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __memsense_imu__IMUDYNPARAMSCONFIG_H__
#define __memsense_imu__IMUDYNPARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace memsense_imu
{
  class IMUDynParamsConfigStatics;

  class IMUDynParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(IMUDynParamsConfig &config, const IMUDynParamsConfig &max, const IMUDynParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const IMUDynParamsConfig &config1, const IMUDynParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, IMUDynParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const IMUDynParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, IMUDynParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const IMUDynParamsConfig &config) const = 0;
      virtual void getValue(const IMUDynParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T IMUDynParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (IMUDynParamsConfig::* field);

      virtual void clamp(IMUDynParamsConfig &config, const IMUDynParamsConfig &max, const IMUDynParamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const IMUDynParamsConfig &config1, const IMUDynParamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, IMUDynParamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const IMUDynParamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, IMUDynParamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const IMUDynParamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const IMUDynParamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, IMUDynParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, IMUDynParamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<IMUDynParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(IMUDynParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("imu_type"==(*_i)->name){imu_type = boost::any_cast<std::string>(val);}
        if("gyros_range"==(*_i)->name){gyros_range = boost::any_cast<double>(val);}
        if("accels_range"==(*_i)->name){accels_range = boost::any_cast<double>(val);}
        if("mags_range"==(*_i)->name){mags_range = boost::any_cast<double>(val);}
        if("serial_port"==(*_i)->name){serial_port = boost::any_cast<std::string>(val);}
        if("gyros_var"==(*_i)->name){gyros_var = boost::any_cast<double>(val);}
        if("accels_var"==(*_i)->name){accels_var = boost::any_cast<double>(val);}
        if("mags_var"==(*_i)->name){mags_var = boost::any_cast<double>(val);}
        if("gyro_bias_x"==(*_i)->name){gyro_bias_x = boost::any_cast<double>(val);}
        if("gyro_bias_y"==(*_i)->name){gyro_bias_y = boost::any_cast<double>(val);}
        if("gyro_bias_z"==(*_i)->name){gyro_bias_z = boost::any_cast<double>(val);}
        if("accel_bias_x"==(*_i)->name){accel_bias_x = boost::any_cast<double>(val);}
        if("accel_bias_y"==(*_i)->name){accel_bias_y = boost::any_cast<double>(val);}
        if("accel_bias_z"==(*_i)->name){accel_bias_z = boost::any_cast<double>(val);}
        if("mag_bias_x"==(*_i)->name){mag_bias_x = boost::any_cast<double>(val);}
        if("mag_bias_y"==(*_i)->name){mag_bias_y = boost::any_cast<double>(val);}
        if("mag_bias_z"==(*_i)->name){mag_bias_z = boost::any_cast<double>(val);}
        if("polling_rate"==(*_i)->name){polling_rate = boost::any_cast<double>(val);}
        if("filter_rate"==(*_i)->name){filter_rate = boost::any_cast<double>(val);}
        if("frame_id"==(*_i)->name){frame_id = boost::any_cast<std::string>(val);}
      }
    }

    std::string imu_type;
double gyros_range;
double accels_range;
double mags_range;
std::string serial_port;
double gyros_var;
double accels_var;
double mags_var;
double gyro_bias_x;
double gyro_bias_y;
double gyro_bias_z;
double accel_bias_x;
double accel_bias_y;
double accel_bias_z;
double mag_bias_x;
double mag_bias_y;
double mag_bias_z;
double polling_rate;
double filter_rate;
std::string frame_id;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string imu_type;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gyros_range;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accels_range;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mags_range;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string serial_port;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gyros_var;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accels_var;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mags_var;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gyro_bias_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gyro_bias_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gyro_bias_z;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_bias_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_bias_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_bias_z;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mag_bias_x;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mag_bias_y;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mag_bias_z;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double polling_rate;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double filter_rate;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string frame_id;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("IMUDynParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const IMUDynParamsConfig &__max__ = __getMax__();
      const IMUDynParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const IMUDynParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const IMUDynParamsConfig &__getDefault__();
    static const IMUDynParamsConfig &__getMax__();
    static const IMUDynParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const IMUDynParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void IMUDynParamsConfig::ParamDescription<std::string>::clamp(IMUDynParamsConfig &config, const IMUDynParamsConfig &max, const IMUDynParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class IMUDynParamsConfigStatics
  {
    friend class IMUDynParamsConfig;

    IMUDynParamsConfigStatics()
    {
IMUDynParamsConfig::GroupDescription<IMUDynParamsConfig::DEFAULT, IMUDynParamsConfig> Default("Default", "", 0, 0, true, &IMUDynParamsConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.imu_type = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.imu_type = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.imu_type = "nIMU_3temp";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<std::string>("imu_type", "str", 3, "IMU device type name", "{'enum_description': 'Memsense IMU device type.', 'enum': [{'srcline': 18, 'description': 'Nano IMU with 3 temperature sensors', 'srcfile': '/home/pi/Desktop/IMU/catkin_workspace/src/memsense_imu/cfg/IMUDynParams.cfg', 'cconsttype': 'const char * const', 'value': 'nIMU_3temp', 'ctype': 'std::string', 'type': 'str', 'name': 'NIMU_3TEMP'}]}", &IMUDynParamsConfig::imu_type)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<std::string>("imu_type", "str", 3, "IMU device type name", "{'enum_description': 'Memsense IMU device type.', 'enum': [{'srcline': 18, 'description': 'Nano IMU with 3 temperature sensors', 'srcfile': '/home/pi/Desktop/IMU/catkin_workspace/src/memsense_imu/cfg/IMUDynParams.cfg', 'cconsttype': 'const char * const', 'value': 'nIMU_3temp', 'ctype': 'std::string', 'type': 'str', 'name': 'NIMU_3TEMP'}]}", &IMUDynParamsConfig::imu_type)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gyros_range = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gyros_range = 1200.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gyros_range = 150.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyros_range", "double", 3, "Gyroscopes' range (deg/sec).", "", &IMUDynParamsConfig::gyros_range)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyros_range", "double", 3, "Gyroscopes' range (deg/sec).", "", &IMUDynParamsConfig::gyros_range)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accels_range = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accels_range = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accels_range = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accels_range", "double", 3, "Accelerometers' range (g).", "", &IMUDynParamsConfig::accels_range)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accels_range", "double", 3, "Accelerometers' range (g).", "", &IMUDynParamsConfig::accels_range)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mags_range = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mags_range = 4.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mags_range = 1.9;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mags_range", "double", 3, "Magnetometers' range (gauss).", "", &IMUDynParamsConfig::mags_range)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mags_range", "double", 3, "Magnetometers' range (gauss).", "", &IMUDynParamsConfig::mags_range)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.serial_port = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.serial_port = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.serial_port = "/dev/ttyUSB0";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<std::string>("serial_port", "str", 1, "Serial port device file name (including full path)", "", &IMUDynParamsConfig::serial_port)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<std::string>("serial_port", "str", 1, "Serial port device file name (including full path)", "", &IMUDynParamsConfig::serial_port)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gyros_var = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gyros_var = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gyros_var = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyros_var", "double", 0, "Gyroscopes' var (deg^2/seg^2).", "", &IMUDynParamsConfig::gyros_var)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyros_var", "double", 0, "Gyroscopes' var (deg^2/seg^2).", "", &IMUDynParamsConfig::gyros_var)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accels_var = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accels_var = 1e-05;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accels_var = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accels_var", "double", 0, "Accelerometers' var (g^2).", "", &IMUDynParamsConfig::accels_var)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accels_var", "double", 0, "Accelerometers' var (g^2).", "", &IMUDynParamsConfig::accels_var)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mags_var = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mags_var = 1e-05;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mags_var = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mags_var", "double", 0, "Magnetometers' var (gauss^2).", "", &IMUDynParamsConfig::mags_var)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mags_var", "double", 0, "Magnetometers' var (gauss^2).", "", &IMUDynParamsConfig::mags_var)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gyro_bias_x = -1.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gyro_bias_x = 1.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gyro_bias_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyro_bias_x", "double", 0, "x gyroscope's bias (deg/sec).", "", &IMUDynParamsConfig::gyro_bias_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyro_bias_x", "double", 0, "x gyroscope's bias (deg/sec).", "", &IMUDynParamsConfig::gyro_bias_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gyro_bias_y = -1.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gyro_bias_y = 1.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gyro_bias_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyro_bias_y", "double", 0, "y gyroscope's bias (deg/sec).", "", &IMUDynParamsConfig::gyro_bias_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyro_bias_y", "double", 0, "y gyroscope's bias (deg/sec).", "", &IMUDynParamsConfig::gyro_bias_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gyro_bias_z = -1.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gyro_bias_z = 1.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gyro_bias_z = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyro_bias_z", "double", 0, "z gyroscope's bias (deg/sec).", "", &IMUDynParamsConfig::gyro_bias_z)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("gyro_bias_z", "double", 0, "z gyroscope's bias (deg/sec).", "", &IMUDynParamsConfig::gyro_bias_z)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_bias_x = -0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_bias_x = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_bias_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accel_bias_x", "double", 0, "x accelerometer's bias (g).", "", &IMUDynParamsConfig::accel_bias_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accel_bias_x", "double", 0, "x accelerometer's bias (g).", "", &IMUDynParamsConfig::accel_bias_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_bias_y = -0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_bias_y = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_bias_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accel_bias_y", "double", 0, "y accelerometer's bias (g).", "", &IMUDynParamsConfig::accel_bias_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accel_bias_y", "double", 0, "y accelerometer's bias (g).", "", &IMUDynParamsConfig::accel_bias_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_bias_z = -0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_bias_z = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_bias_z = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accel_bias_z", "double", 0, "z accelerometer's bias (g).", "", &IMUDynParamsConfig::accel_bias_z)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("accel_bias_z", "double", 0, "z accelerometer's bias (g).", "", &IMUDynParamsConfig::accel_bias_z)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mag_bias_x = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mag_bias_x = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mag_bias_x = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mag_bias_x", "double", 0, "x magnetometer's bias (gauss).", "", &IMUDynParamsConfig::mag_bias_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mag_bias_x", "double", 0, "x magnetometer's bias (gauss).", "", &IMUDynParamsConfig::mag_bias_x)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mag_bias_y = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mag_bias_y = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mag_bias_y = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mag_bias_y", "double", 0, "y magnetometer's bias (gauss).", "", &IMUDynParamsConfig::mag_bias_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mag_bias_y", "double", 0, "y magnetometer's bias (gauss).", "", &IMUDynParamsConfig::mag_bias_y)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mag_bias_z = -1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mag_bias_z = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mag_bias_z = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mag_bias_z", "double", 0, "z magnetometer's bias (gauss).", "", &IMUDynParamsConfig::mag_bias_z)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("mag_bias_z", "double", 0, "z magnetometer's bias (gauss).", "", &IMUDynParamsConfig::mag_bias_z)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.polling_rate = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.polling_rate = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.polling_rate = 150.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("polling_rate", "double", 0, "Polling rate (set the device maximum output to avoid busy waits (0.0 disables polling)", "", &IMUDynParamsConfig::polling_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("polling_rate", "double", 0, "Polling rate (set the device maximum output to avoid busy waits (0.0 disables polling)", "", &IMUDynParamsConfig::polling_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.filter_rate = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.filter_rate = 50.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.filter_rate = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("filter_rate", "double", 0, "Rate for filtered data publications (0.0 disables filtering)", "", &IMUDynParamsConfig::filter_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<double>("filter_rate", "double", 0, "Rate for filtered data publications (0.0 disables filtering)", "", &IMUDynParamsConfig::filter_rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frame_id = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frame_id = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frame_id = "imu";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<std::string>("frame_id", "str", 0, "Frame in which IMU readings will be returned", "", &IMUDynParamsConfig::frame_id)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(IMUDynParamsConfig::AbstractParamDescriptionConstPtr(new IMUDynParamsConfig::ParamDescription<std::string>("frame_id", "str", 0, "Frame in which IMU readings will be returned", "", &IMUDynParamsConfig::frame_id)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(IMUDynParamsConfig::AbstractGroupDescriptionConstPtr(new IMUDynParamsConfig::GroupDescription<IMUDynParamsConfig::DEFAULT, IMUDynParamsConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<IMUDynParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<IMUDynParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<IMUDynParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    IMUDynParamsConfig __max__;
    IMUDynParamsConfig __min__;
    IMUDynParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const IMUDynParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static IMUDynParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &IMUDynParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const IMUDynParamsConfig &IMUDynParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const IMUDynParamsConfig &IMUDynParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const IMUDynParamsConfig &IMUDynParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<IMUDynParamsConfig::AbstractParamDescriptionConstPtr> &IMUDynParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<IMUDynParamsConfig::AbstractGroupDescriptionConstPtr> &IMUDynParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const IMUDynParamsConfigStatics *IMUDynParamsConfig::__get_statics__()
  {
    const static IMUDynParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = IMUDynParamsConfigStatics::get_instance();

    return statics;
  }

//#line 18 "/home/pi/Desktop/IMU/catkin_workspace/src/memsense_imu/cfg/IMUDynParams.cfg"
      const char * const IMUDynParams_NIMU_3TEMP = "nIMU_3temp";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __IMUDYNPARAMSRECONFIGURATOR_H__
