// Generated by gencpp from file memsense_imu/ImuMAG.msg
// DO NOT EDIT!


#ifndef MEMSENSE_IMU_MESSAGE_IMUMAG_H
#define MEMSENSE_IMU_MESSAGE_IMUMAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace memsense_imu
{
template <class ContainerAllocator>
struct ImuMAG_
{
  typedef ImuMAG_<ContainerAllocator> Type;

  ImuMAG_()
    : header()
    , angular_velocity()
    , angular_velocity_covariance()
    , linear_acceleration()
    , linear_acceleration_covariance()
    , magnetic_field()
    , magnetic_field_covariance()  {
      angular_velocity_covariance.assign(0.0);

      linear_acceleration_covariance.assign(0.0);

      magnetic_field_covariance.assign(0.0);
  }
  ImuMAG_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angular_velocity(_alloc)
    , angular_velocity_covariance()
    , linear_acceleration(_alloc)
    , linear_acceleration_covariance()
    , magnetic_field(_alloc)
    , magnetic_field_covariance()  {
  (void)_alloc;
      angular_velocity_covariance.assign(0.0);

      linear_acceleration_covariance.assign(0.0);

      magnetic_field_covariance.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef boost::array<double, 9>  _angular_velocity_covariance_type;
  _angular_velocity_covariance_type angular_velocity_covariance;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef boost::array<double, 9>  _linear_acceleration_covariance_type;
  _linear_acceleration_covariance_type linear_acceleration_covariance;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _magnetic_field_type;
  _magnetic_field_type magnetic_field;

   typedef boost::array<double, 9>  _magnetic_field_covariance_type;
  _magnetic_field_covariance_type magnetic_field_covariance;





  typedef boost::shared_ptr< ::memsense_imu::ImuMAG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::memsense_imu::ImuMAG_<ContainerAllocator> const> ConstPtr;

}; // struct ImuMAG_

typedef ::memsense_imu::ImuMAG_<std::allocator<void> > ImuMAG;

typedef boost::shared_ptr< ::memsense_imu::ImuMAG > ImuMAGPtr;
typedef boost::shared_ptr< ::memsense_imu::ImuMAG const> ImuMAGConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::memsense_imu::ImuMAG_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::memsense_imu::ImuMAG_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace memsense_imu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'memsense_imu': ['/home/pi/Desktop/IMU/catkin_workspace/src/memsense_imu/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::memsense_imu::ImuMAG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::memsense_imu::ImuMAG_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::memsense_imu::ImuMAG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::memsense_imu::ImuMAG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::memsense_imu::ImuMAG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::memsense_imu::ImuMAG_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::memsense_imu::ImuMAG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e08da8dd92dede637afd3f4b4d9bf2c";
  }

  static const char* value(const ::memsense_imu::ImuMAG_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e08da8dd92dede6ULL;
  static const uint64_t static_value2 = 0x37afd3f4b4d9bf2cULL;
};

template<class ContainerAllocator>
struct DataType< ::memsense_imu::ImuMAG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "memsense_imu/ImuMAG";
  }

  static const char* value(const ::memsense_imu::ImuMAG_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::memsense_imu::ImuMAG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Version of sensor_msgs/Imu message \n\
# with added magnetometer and temperature readings.\n\
\n\
Header header\n\
\n\
geometry_msgs/Vector3 angular_velocity\n\
float64[9] angular_velocity_covariance # Row major about x, y, z axes\n\
\n\
geometry_msgs/Vector3 linear_acceleration\n\
float64[9] linear_acceleration_covariance # Row major x, y z\n\
\n\
geometry_msgs/Vector3 magnetic_field\n\
float64[9] magnetic_field_covariance # Row major x, y z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::memsense_imu::ImuMAG_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::memsense_imu::ImuMAG_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angular_velocity);
      stream.next(m.angular_velocity_covariance);
      stream.next(m.linear_acceleration);
      stream.next(m.linear_acceleration_covariance);
      stream.next(m.magnetic_field);
      stream.next(m.magnetic_field_covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuMAG_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::memsense_imu::ImuMAG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::memsense_imu::ImuMAG_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "angular_velocity_covariance[]" << std::endl;
    for (size_t i = 0; i < v.angular_velocity_covariance.size(); ++i)
    {
      s << indent << "  angular_velocity_covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angular_velocity_covariance[i]);
    }
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "linear_acceleration_covariance[]" << std::endl;
    for (size_t i = 0; i < v.linear_acceleration_covariance.size(); ++i)
    {
      s << indent << "  linear_acceleration_covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.linear_acceleration_covariance[i]);
    }
    s << indent << "magnetic_field: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.magnetic_field);
    s << indent << "magnetic_field_covariance[]" << std::endl;
    for (size_t i = 0; i < v.magnetic_field_covariance.size(); ++i)
    {
      s << indent << "  magnetic_field_covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.magnetic_field_covariance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MEMSENSE_IMU_MESSAGE_IMUMAG_H
